ruby-no-kai/rko-router

config/nginx.conf.erb
add the proxy_pass setting for kansai06 teaser site
=> add proxy_pass for kansai06

config/nginx.conf.erb
add proxy_pass for TokyuRubyKaigi09
=> add proxy_pass for tokyurubykaigi09

config/nginx.conf.erb
=> Add Server for cfp.rubykaigi.org

config/nginx.conf.erb
Add server cfp.rubykaigi.org which redirect to https://rubykaigi-cfp.herokuapp.com.
=> Add server cfp.rubykaigi.org

config/nginx.conf.erb
松江Ruby会議07へのリダイレクト設定を追加しました。マージよろしくお願いいたします。
=> Add redirect to matsue07.

config/nginx.conf.erb
=> Redirect oedo05

config/nginx.conf.erb, spec/rubykaigi_org_spec.rb
=> Launch rubykaigi.org/2016

config/nginx.conf.erb
=> Add tokyo11

config/nginx.conf.erb
tokyu10 告知サイトへの転送設定を追加させてください :beers:
=> Add tokyu10

config/nginx.conf.erb
=> Deploying RK 2016 site to another Heroku app for now

config/nginx.conf.erb
This reverts commit ac28443b3943f6dc0e77cef7729f380d05069d6e.
=> Revert "Deploying RK 2016 site to another Heroku app for now"

config/nginx.conf.erb
=> retry rk2016

config/nginx.conf.erb
松江Ruby会議08が12/17に開催予定です。
松江Ruby会議08のWebサイトへのリダイレクト設定を追加しました。
マージよろしくお願い致します。
=> Add redirect to matsue08.

config/nginx.conf.erb
https://asakusarb.github.io/oedo06/
=> Oedo06 is hosted on Asakusa.rb's gh-pages

config/nginx.conf.erb
=> RubyKaigi 2017

config/nginx.conf.erb
tokyu11 告知サイトへの転送設定を追加させてください 🍻
https://tokyurubykaigi.github.io/tokyu11/
=> Add tokyu11

spec/rubykaigi_org_spec.rb
=> update to 2017

config/nginx.conf.erb
http://rubykaigi2018.herokuapp.com/2018 を町田さんにサクッと作ってもらったので、ルーティングしたいです。
=> Route to rubykaigi2018

config/nginx.conf.erb
redirect 先を最新にしました。
https://github.com/ruby-no-kai/rubykaigi2018/pull/15
をマージ次第 master に取り込んでいただければと思います。
=> Change redirect link from /2017 to /2018

config/nginx.conf.erb
大阪Ruby会議01の転送設定の追加をお願いします。
https://rubykansai.github.io/osaka01/
=> Add osaka01

Gemfile, Gemfile.lock
`bundle exec rake spec` でコケないようにするものです
=> support rake in Gemfile

spec/rubykaigi_org_spec.rb
#30 の時にspecが更新されてなかったので、その後の変更も合わせて対応するものです
=> update specs for github pages edition

Gemfile, Gemfile.lock
=> use latest Rake

config/nginx.conf.erb
TokyuRuby会議12への転送設定を追加しました。
https://tokyurubykaigi.github.io/tokyu12/
=> Add tokyu12

config/nginx.conf.erb
=> Route to rubykaigi2019

.buildpacks
=> Use the latest nginx-buildpack

config/nginx.conf.erb
https://asakusarb.github.io/oedo07/ を追加するやつです。
=> url_for oedo07

config/nginx.conf.erb
@sorah 2019のサイトをデプロイしてみたけど、2019配下のassetsが見えてなさそうです。昨日masterに積まれてたコミット3つをとりあえずrevertしときますね。
=> Revert 2019 changes

config/nginx.conf.erb
Now that we have the team page and the policies page, I guess the 2019 page is ready.
=> root to: rubykaigi2019

config/nginx.conf.erb
=> Move 2018 from Heroku to static

config/nginx.conf.erb
=> Move 2019 from Heroku to static

config/nginx.conf.erb
map.connect 'oedo08' => 'https://asakusarb.github.io/oedo08/'
=> url_for(大江戸Ruby会議08)

config/nginx.conf.erb
2008はまだサルベージできてないですが、http://jp.rubyist.net も消滅しているので先にこちらを用意しておくか…という気持ちです。
=> Fix routing; RubyKaigi 200x should be static

config/nginx.conf.erb
https://github.com/ruby-no-kai/rubykaigi-static/pull/10
=> Archive /2020, /2020-takeout

config/nginx.conf.erb
=> Now 2021-takeout is latest

.github/workflows/ci.yml, config/nginx.conf.erb, tf/apprunner.tf, tf/ci.tf
https://github.com/ruby-no-kai/rko-router/issues/81
=> AWS App Runner

config/nginx.conf.erb
- long max-age
- long s-maxage
=> adjust cache-control for past kaigis

config/nginx.conf.erb, spec/rubykaigi_org_spec.rb
=> Ready for 2023

README.md, config/nginx.conf.erb
this gives verified status on our link set to Mastodon https://ruby.social/@rubykaigi profile.
=> /: add <link rel=me> to Mastodon account

config/nginx.conf.erb
=> Fix typo :pray:

config/nginx.conf.erb, spec/regional_rubykaigi_org_spec.rb
=> 大江戸Ruby会議10

config/nginx.conf.erb
https://regional.rubykaigi.org/oedo10 とかをforce_httpsしたくて。
=> Force HTTPS for oedo pages on GH Pages

config/nginx.conf.erb, spec/rubykaigi_org_spec.rb
=> root to: 2024

config/nginx.conf.erb, spec/regional_rubykaigi_org_spec.rb
ref: https://github.com/ruby-no-kai/official/issues/508
東京Ruby会議12のページにプロキシします。よろしくお願いします。
=> 東京Ruby会議12

config/nginx.conf.erb
ながらRuby会議01 の設定を追加しました
https://corocn.github.io/nagara01/
=> Add nagara01

config/nginx.conf.erb
北陸Ruby会議01 https://github.com/ruby-no-kai/official/issues/538 の設定を追加しました。
=> Add hokuriku01

config/nginx.conf.erb
関西Ruby会議09の転送設定の追加をお願いします。
https://rubykansai.github.io/kansai09/
=> Add kansai09
