ruby-no-kai/rko-router

config/nginx.conf.erb
This reverts commit c97f26cdfeb21b0d644e4b7283f5622966b2687a.
We pointed cfp.rubykaigi.org to Heroku directly with CNAME.
=> Revert "Add cfp.rubykaigi.org"

config/nginx.conf.erb
川崎Ruby会議01(kwsk01)のページへの転送設定を追加させて下さい。
転送先: http://kawasakirb.github.io/kwsk01/
=> Add kwsk01

config/nginx.conf.erb
関西Ruby会議2017 の proxy_pass を追加しました。
https://rubykansai.github.io/kansai2017/
=> Route to Kansai RubyKaigi 2017

.buildpacks
#23 のために、まずはhttpsに`proxy_pass`できるようにします。
ryandotsmith/nginx-buildpackがhttp_ssl_moduleを組み込んでいないので、
向こうに出ていたPRをあてたやつを使うようにします。
see also: https://github.com/kakutani/nginx-buildpack/pull/1
=> Enable http_ssl_module and update nginx and pcre version #23

config/nginx.conf.erb
linode.rubykaigi.org を捨てて github pages (https://github.com/ruby-no-kai/rubykaigi-static) を使うようにするための修正です。
=> move from linode to github pages

config/nginx.conf.erb
cf.) #34 
https://github.com/ruby-no-kai/rubykaigi2018/issues/18#issuecomment-358261897
にまつわるタスクです。
2017 年用のフォーム URL にリダイレクトされていたのを 2018 年用のフォームに変更しました
URL が微妙に違うのですが、フォームとしては
https://docs.google.com/forms/d/e/1FAIpQLSfkgH_vh_qu-KJN-w7zJOKtHKginbTSB_8fqzOlcqm9wOJtxw/viewform
で良いのですよね？
=> Change redirect url for sponsors from 2017 to 2018

config/nginx.conf.erb
cf.) https://github.com/ruby-no-kai/rubykaigi2018/issues/34
- コメントアウトの変更漏れ修正
- 前回の PR のときにやっておけばよかったです...
- sponsorships でもリダイレクトできるような変更
- 2 ストライク 3 アウト制を信じているので、この程度ならかっこよく reg exp を使わずそのままで行く
- nginx.conf 全然触ったこと無いので、これであってるか見てほしいです
=> Add server_name setting to redirect from sponsorships

config/nginx.conf.erb
更新の止まって久しい RubyKaigi 2013, 2014, 2016, 2017 の各サイトを Heroku から rubykaigi-static に切り替えたいです。rubykaigi-static には push 済みです。
ただし、2015だけは、僕の手元で `bundle e rake build`して生成されたものを rubykaigi-static に置いてみたところ、scheduleから 各 presentation へのリンクがぶっ壊れていて、
https://2009-2011.rubykaigi.org/2015/schedule/
よくわかんないのでいったんそのままにしてあります。
=> Moving past Kaigis from Heroku to pages

config/nginx.conf.erb
TokyuRuby会議13への転送設定を追加しました。
転送先: https://tokyurubykaigi.github.io/tokyu13/
開催issue: https://github.com/ruby-no-kai/official/issues/335 TokyuRuby 会議 13 の開催
=> Add tokyu13

config/nginx.conf.erb
oedo02のリダイレクト先を追加するパッチです。
もともとoedo02のイベント自体のサイトは存在していなくて、たなべさんが書いたるびまの記事が大江戸02と呼ばれるイベントの公式サイトということになっていました。
で、そのためのリダイレクトをここのHTML内でやってたんですけど、このHTMLが長らく更新されてなくて旧るびまURLのままになっていたようです。 https://github.com/ruby-no-kai/regional.rubykaigi.org/blob/3606496af0c9702c4fd6b9daef1bcebfcc57b12d/oedo02/index.html
というのが、今晩のAsakusa.rbのmeetupで発覚して、しかしどうせリダイレクトしてるだけだったらGH Pagesをかまさずにrko-routerに直接書けばよくね？という話になったのでした。
……って書いてるうちに[こっちはこっちで](https://github.com/ruby-no-kai/regional.rubykaigi.org/pull/119)なんか直しちゃったようですけど、まあしかしやっぱりGH Pagesのほうはそもそも不要になるんじゃないかな……。
/cc @takkanm @kakutani
=> Redirect oedo02 directly from the router rather than bypassing GH Pages

config/nginx.conf.erb
現状、 https://regional.rubykaigi.org/oedo04/ にアクセスするといつの間にか "Not Found" ってなるようになってたようで、でもproxy先の https://oedo04.herokuapp.com/ を直接見るとちゃんと動いてそうで、最近やったことと言ったらアプリを heroku-18 stackに上げたことぐらいなんだけど、それに伴ってHeroku側がHTTPSになったはずなので、こっちも https://... って書いておかなきゃいけないのかな？というやつです。
いずれにしろ、すぐにでもstaticに持っていきたいのでもうこの際そっちを進めちゃえばいいんじゃないかな、とは思いつつ、壊れた状態のものはいったん直してみたいので、これでどうでしょうか？的なパッチを投げてみます。
=> oedo04 is HTTPS only now

config/nginx.conf.erb
https://github.com/ruby-no-kai/regional.rubykaigi.org/pull/122 でoedo04のHerokuアプリをstatic化したので、そっちにルーティングするようにします。
=> route :oedo04, :to => regional-gh

config/nginx.conf.erb
.2008 は https://github.com/ruby-no-kai/rubykaigi-static/pull/55 で削除されました。
.2006 は 5a2b9fd805b6b67e9e49d85e998ce6eca7af6531 で Linode に置いてあった時点では何か存在してたのかもしれませんが、ruby-kaigi-static のリポジトリ上ではそういう名前のディレクトリが存在した歴史はなさそうだし、リポジトリ内を `git grep` してみても、ここのファイルが参照されてたり何かリクエストが飛びそうだったりはしなさそうです。
=> ルーティングされてなさそうな .2006 と .2008 の削除

config/nginx.conf.erb
0385d95f039d210bf10c962925ce0612a38182c7 の時点では何やらいろいろあったようなんですが、現時点ではそういうURLへのリクエストは来なそうだし、仮に来たところでもう herokuapp.com 上の各年のアプリが生きてるとは限らなそうだし、これはもう死んでるルールでしょう。
=> ^/assets/(20[1-9][3-9]) っていう使われてないrewriteの削除

config/nginx.conf.erb
2006.rubykaigi.org とかにアクセスすると、jp.rubyist.net に飛んでいってしまう設定が残ってるんですが、これを rubykaigi-static に飛ぶように修正しています。
実際にこういうリクエストが今でもあるのかどうかは知りません、というかたぶん無さそうな気はしてますけど。
=> Redirect 200[6-8].rubykaigi.org  =>  rubykaigi-static

config/nginx.conf.erb
2021-takeoutのサイトを、https://github.com/ruby-no-kai/rubykaigi-static/pull/58 でアーカイブしたやつに切り替えます。
=> Archive 2021-takeout

.gitignore, Dockerfile, tf/.terraform.lock.hcl, tf/acm.tf, tf/aws.tf, tf/cf_functions/package-lock.json, tf/cf_functions/package.json, tf/cf_functions/src/viewreq.ts, tf/cf_functions/tsconfig.json, tf/cloudfront.tf, tf/versions.tf
default server and x-rko-host mechanism, which was originally introduced for testing, is now also used in App Runner & CloudFront deployment. This is due to the quota of custom domains per App Runner service.
CloudFront function is used for assigning x-rko-host before forwarding to the origin on App Runner.
https://github.com/ruby-no-kai/rko-router/issues/81
=> Add CloudFront distribution for App Runner deployment

.dockerignore, .gitattributes, README.md, config/force_https.conf, config/nginx.conf.erb, spec/rubykaigi_org_spec.rb, spec/support/http_client.rb
- update tests to test force_https behavior more precisely
- declare proxy_redirect to avoid redirecting to http:// url for force_https enabled paths
- this would avoid the dance like https://rubykaigi.org/200x => http://rubykaigi.org/200x/ => https://rubykaigi.org/200x/.
- gh-pages returns http URL for trailing slash redirection (why?)
- Heroku may be doing something like this on their proxy layer, but App Runner does not.
https://github.com/ruby-no-kai/rko-router/issues/81
=> fix http redirection on App Runner

config/force_https.conf
ruby-no-kai/official#443 の問題を解決したい
=> regional.rubykaigi.org もforce sslしたい

config/nginx.conf.erb, spec/regional_rubykaigi_org_spec.rb
* http://regional.rubykaigi.org -> https://regional.rubykaigi.org  #に転送されて、ruby-no-kai/regional.rubykaigi.org  の配下にあるGH pagesなコンテンツが表示されてほしい。
* 現状、`regional-gh.rubykaigi.org` の force ssl の ✅ は on にしています
* ふんいきで #88 を足すだけでは rrk.org を force ssl するには足りなかった(雑にPRを投げてしまった…)
* その後、改めて https://rubykaigi.esa.io/posts/1241 に目を通してみた(仕組みの全容は掴めておりません。プロ仕様だ…)
* rk.org の設定のように `include force_https.conf;` すればいいのかなあと思ったけど、rrk.org は `'/'` → current のような転送はしていないので、コピペ改変では `regional_rubykaigi_org_spec.rb`はfailureになってしまった…
* @sorah のお知恵を拝借したく!!
=> "regional.rubykaigi.org もforce sslしたい" Redux

.github/workflows/ci.yml
This eliminates the following warning:
"Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: aws-actions/configure-aws-credentials@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/."
e.g. https://github.com/ruby-no-kai/rko-router/actions/runs/5003764840
=> Bump aws-actions/configure-aws-credentials to v2 that uses Node.js 16

config/nginx.conf.erb
TokyuRuby会議14への転送設定を追加しました。
転送先: https://tokyurubykaigi.github.io/tokyu14/
開催issue: https://github.com/ruby-no-kai/official/issues/476 TokyuRuby 会議 14 の開催
=> Add tokyu14

config/nginx.conf.erb
大阪Ruby会議04の転送設定の追加をお願いします。
https://rubykansai.github.io/osaka04/
=> Add osaka04

spec/regional_rubykaigi_org_spec.rb
Follow-up of https://github.com/ruby-no-kai/rko-router/pull/110.
asakusa.github.io has (unintentionally) moved to asakusa.rubyist.net. https://github.com/ruby-no-kai/rko-router/pull/110#issuecomment-2264721392
=> Temporarily ignore tests for /oedo(05|06|10)/

config/nginx.conf.erb
Follow-up of https://github.com/ruby-no-kai/rko-router/pull/110.
`https://regional.rubykaigi.org/tokyo12/` が 200 になる一方、 `https://regional.rubykaigi.org/tokyo12` (trailing slash なし) が `https://osyoyu.github.io/tokyo12/` への 302 になってしまうのを解消したいパッチです。 `osyoyu.github.io` はなるべく露出させたくない。
- trailing slash がない場合、trailing slash ありのパスに 302 するのは GitHub Pages の仕様
- そのときの Location が `osyoyu.github.io` になる（GitHub Pages は regional.rubykaigi.org からプロキシされていることを当然知らないから）
そこで……
- GitHub Pages の [custom domain](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site) に `regional.rubykaigi.org` を設定した
- `CNAME` ファイルを置くやつ
- なお verification は（当然）通していない
- すると GitHub Pages は `regional.rubykaigi.org` でホストされている前提の挙動になる
- trailing slash なしのアクセス時の 302 の Location も `regional.rubykaigi.org` …
=> tokyo12: proxy_set_header Host $http_host

config/nginx.conf.erb
https://github.com/ruby-no-kai/rko-router/pull/112 の変更、GitHub Pages 側が HTTPS だとうまくいかない気配があったので戻します……。
=> tokyo12: No proxy_set_header

config/nginx.conf.erb, spec/regional_rubykaigi_org_spec.rb
過去のoedoのいくつかのサイトのカスタムドメイン設定がうまくいってない問題 https://github.com/ruby-no-kai/rko-router/pull/110#issuecomment-2264627864
の対応で、oedo05をregional.r-k.o に移動することにします。
=> Host oedo05 at regional.r-k.o

config/nginx.conf.erb
関西Ruby会議08の転送設定の追加をお願いします。
https://rubykansai.github.io/kansai08/
=> Add kansai08

config/nginx.conf.erb
https://regional.rubykaigi.org/tokyo12/ の裏側の GitHub Pages のリポジトリを osyoyu/tokyo12 から tokyorubykaigi12/tokyo12 に引っ越ししたいので proxy_pass 先を変更します。
現時点で https://osyoyu.github.io/tokyo12/ と https://tokyorubykaigi12.github.io/tokyo12/ の両方で同じコンテンツをホストしているのでいつマージしてもらっても大丈夫です。
=> Move tokyo12 page to tokyorubykaigi12 org
